# -*- coding: utf-8 -*-
"""test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyzL-Bm4ESP8y0WYjq_3jsdzJ0gjTIGk
"""

# Prueba de Python

a = 10
b = 30
c = a * b
print('Resultado =', c)